const listOtrosProductos = [
  {
    id: 1,
    src: require("@/images/otrosproductos/img113.jpeg"),
    name: "Bolsa con impresión y bordes y asas de tela",
    code: "LM-TP001",
    flex: 12,
  },
  {
    id: 2,
    src: require("@/images/otrosproductos/img114.jpeg"),
    name: "Mochila de poliester con portalaptop",
    code: "LM-TP002",
    flex: 12,
  },
  {
    id: 3,
    src: require("@/images/otrosproductos/img115.jpeg"),
    name: "Mochila de poliester con portalaptop colores variados",
    code: "LM-TP003",
    flex: 12,
  },
  {
    id: 4,
    src: require("@/images/otrosproductos/img109.png"),
    name: "Bolsa de algodón con asas de yute natural e impresión",
    code: "LM-TP004",
    flex: 12,
  },
  {
    id: 5,
    src: require("@/images/otrosproductos/img110.png"),
    name: "Bolsa de algodón natural, grande con fuelles y base de 25cm aprox y logo impreso en la delantera",
    code: "LM-TP005",
    flex: 12,
  },
  {
    id: 6,
    src: require("@/images/otrosproductos/img111.png"),
    name: "Vasos térmicos con tapa",
    code: "LM-TP006",
    flex: 12,
  },
  {
    id: 7,
    src: require("@/images/otrosproductos/img112.png"),
    name: "Medalla",
    code: "LM-TP007",
    flex: 12,
  },
  {
    id: 9,
    src: require("@/images/otrosproductos/img107.png"),
    name: "Lápiz natural con impresión a un color",
    code: "LM-TP008",
    flex: 12,
  },
  {
    id: 114,
    src: require("@/images/otrosproductos/img108.png"),
    name: "Canguros cuero",
    code: "LM-TP009",
    flex: 12,
  },
  {
    id: 8,
    src: require("@/images/otrosproductos/img8.png"),
    code: "LM-TP010",
    name: "Taza con cuchara en material de fibra de trigo",
    flex: 12,
  },
  {
    id: 9,
    src: require("@/images/otrosproductos/img9.png"),
    code: "LM-TP011",
    name: "Taza con cuchara en material de fibra de trigo",
    flex: 12,
  },
  {
    id: 10,
    src: require("@/images/otrosproductos/img106.png"),
    code: "LM-TP012",
    name: "Identificador maleta en bio-cuero con telar",
    flex: 12,
  },
  {
    id: 11,
    src: require("@/images/otrosproductos/img11.png"),
    code: "LM-TP013",
    name: "Resaltador multi-color",
    flex: 12,
  },
  {
    id: 117,
    src: require("@/images/otrosproductos/img30.png"),
    code: "LM-TP014",
    name: "Tarjetero en cobre",
    flex: 12,
  },
  {
    id: 12,
    src: require("@/images/otrosproductos/img12.png"),
    code: "LM-TP015",
    name: "Pizarra de corcho y acrílico",
    flex: 12,
  },

  {
    id: 13,
    src: require("@/images/otrosproductos/img13.png"),
    code: "LM-TP016",
    name: "Luces de seguridad para zapatilla",
    flex: 12,
  },
  {
    id: 14,
    src: require("@/images/otrosproductos/img14.png"),
    code: "LM-TP017",
    name: "Tomatodo de fibra de trigo ecológico",
    flex: 12,
  },
  {
    id: 15,
    src: require("@/images/otrosproductos/img15.png"),
    code: "LM-TP018",
    name: "Set para vinos",
    flex: 12,
  },
  {
    id: 16,
    src: require("@/images/otrosproductos/img16.png"),
    code: "LM-TP019",
    name: "Pizarra con corcho",
    flex: 12,
  },
  {
    id: 17,
    src: require("@/images/otrosproductos/img17.png"),
    code: "LM-TP020",
    name: "Vaso taza de fibra de trigo ecológico",
    flex: 12,
  },
  {
    id: 18,
    src: require("@/images/otrosproductos/img18.png"),
    code: "LM-TP021",
    name: "Mug térmico",
    flex: 12,
  },
  {
    id: 19,
    src: require("@/images/otrosproductos/img19.png"),
    code: "LM-TP022",
    name: "Maletín 100% cuero",
    flex: 12,
  },
  {
    id: 20,
    src: require("@/images/otrosproductos/img20.png"),
    code: "LM-TP023",
    name: "Tarjetero para celular",
    flex: 12,
  },
  {
    id: 21,
    src: require("@/images/otrosproductos/img21.png"),
    code: "LM-TP024",
    name: "Tomatodo de fibra de trigo",
    flex: 12,
  },
  {
    id: 22,
    src: require("@/images/otrosproductos/img22.png"),
    code: "LM-TP025",
    name: "Tomado de fibra de trigo con vidrio en el interior",
    flex: 12,
  },
  {
    id: 23,
    src: require("@/images/otrosproductos/img23.png"),
    code: "LM-TP026",
    name: "Shaker tomatodo",
    flex: 12,
  },
  {
    id: 24,
    src: require("@/images/otrosproductos/img24.png"),
    code: "LM-TP027",
    name: "Neceser de cuero repujado",
    flex: 12,
  },
  {
    id: 25,
    src: require("@/images/otrosproductos/img25.png"),
    code: "LM-TP028",
    name: "Parante publicitario en acrilico",
    flex: 12,
  },
  {
    id: 26,
    src: require("@/images/otrosproductos/img26.png"),
    code: "LM-TP029",
    name: "Libreta-agenda cuero 100%",
    flex: 12,
  },
  {
    id: 27,
    src: require("@/images/otrosproductos/img27.png"),
    code: "LM-TP030",
    name: "Libreta biodegradable con lapicero y post-it",
    flex: 12,
  },
  {
    id: 31,
    src: require("@/images/otrosproductos/img31.jpg"),
    code: "LM-TP031",
    name: "Vaso en acrílico",
    flex: 12,
  },
  {
    id: 32,
    src: require("@/images/otrosproductos/img32.png"),
    code: "LM-TP032",
    name: "Separador de libros",
    flex: 12,
  },
  {
    id: 33,
    src: require("@/images/otrosproductos/img33.png"),
    code: "LM-TP033",
    name: "Porta documentos y tarjeteros en bio-cuero",
    flex: 12,
  },
  {
    id: 34,
    src: require("@/images/otrosproductos/img34.jpg"),
    code: "LM-TP034",
    name: "Porta tarjetas con filo de metal",
    flex: 12,
  },
  {
    id: 35,
    src: require("@/images/otrosproductos/img35.jpg"),
    code: "LM-TP035",
    name: "Lapicero con impresión",
    flex: 12,
  },
  {
    id: 36,
    src: require("@/images/otrosproductos/img36.jpg"),
    code: "LM-TP036",
    name: "Lápiz ecológico",
    flex: 12,
  },
  {
    id: 37,
    src: require("@/images/otrosproductos/img37.jpg"),
    code: "LM-TP037",
    name: "Lapicero y resaltador con impresión",
    flex: 12,
  },
  {
    id: 38,
    src: require("@/images/otrosproductos/img38.png"),
    code: "LM-TP038",
    name: "Lapicero Inoxcrom con impresión",
    flex: 12,
  },
  {
    id: 39,
    src: require("@/images/otrosproductos/img39.png"),
    code: "LM-TP039",
    name: "Carpeta en bio-cuero con telar",
    flex: 12,
  },
  {
    id: 40,
    src: require("@/images/otrosproductos/img40.jpg"),
    code: "LM-TP040",
    name: "Imprenta y papelería",
    flex: 12,
  },
  {
    id: 41,
    src: require("@/images/otrosproductos/img41.png"),
    code: "LM-TP041",
    name: "Carpeta en cuero 100%",
    flex: 12,
  },
  {
    id: 42,
    src: require("@/images/otrosproductos/img42.png"),
    code: "LM-TP042",
    name: "Portavasos con telar en cuero y bio-cuero con correa para cerrado",
    flex: 12,
  },
  {
    id: 43,
    src: require("@/images/otrosproductos/img43.png"),
    code: "LM-TP043",
    name: "Tarjetero para mesa de bio-cuero con telar",
    flex: 12,
  },
  {
    id: 44,
    src: require("@/images/otrosproductos/img44.png"),
    code: "LM-TP044",
    name: "Monederos en cuero y bio-cuero",
    flex: 12,
  },
  {
    id: 45,
    src: require("@/images/otrosproductos/img45.png"),
    code: "LM-TP045",
    name: "Posavasos con telar en cuero y bio-cuero",
    flex: 12,
  },
  {
    id: 46,
    src: require("@/images/otrosproductos/img46.png"),
    code: "LM-TP046",
    name: "Porta retrato en bio-cuero con telar",
    flex: 12,
  },
  {
    id: 47,
    src: require("@/images/otrosproductos/img47.png"),
    code: "LM-TP047",
    name: "Porta libreta con telar en bio-cuero",
    flex: 12,
  },
  {
    id: 48,
    src: require("@/images/otrosproductos/img48.png"),
    code: "LM-TP048",
    name: "Cartera en cuero con logo interno",
    flex: 12,
  },
  {
    id: 49,
    src: require("@/images/otrosproductos/img49.png"),
    code: "LM-TP049",
    name: "Boligrafo metal con logotipo color",
    flex: 12,
  },
  {
    id: 50,
    src: require("@/images/otrosproductos/img50.png"),
    code: "LM-TP050",
    name: "Vasos en vidrio y acrílico con impresión",
    flex: 12,
  },
  {
    id: 51,
    src: require("@/images/otrosproductos/img51.jpg"),
    code: "LM-TP051",
    name: "Libreta con hojas rayadas",
    flex: 12,
  },
  {
    id: 52,
    src: require("@/images/otrosproductos/img52.png"),
    code: "LM-TP052",
    name: "Libretas en carton con logo impreso",
    flex: 12,
  },
  {
    id: 53,
    src: require("@/images/otrosproductos/img53.png"),
    code: "LM-TP053",
    name: "Posavasos carton duplex con impresión y removedores de acrilico",
    flex: 12,
  },
  {
    id: 54,
    src: require("@/images/otrosproductos/img54.png"),
    code: "LM-TP054",
    name: "Productos en vidrio y vitrofusion",
    flex: 12,
  },
  {
    id: 55,
    src: require("@/images/otrosproductos/img55.png"),
    code: "LM-TP055",
    name: "Bolsa bio-degradable para documentos",
    flex: 12,
  },
  {
    id: 56,
    src: require("@/images/otrosproductos/img56.png"),
    code: "LM-TP056",
    name: "Marco de fotos en cuero",
    flex: 12,
  },
  {
    id: 57,
    src: require("@/images/otrosproductos/img57.png"),
    code: "LM-TP057",
    name: "Libretas papel",
    flex: 12,
  },
  {
    id: 58,
    src: require("@/images/otrosproductos/img58.png"),
    code: "LM-TP058",
    name: "Billetera de cuero",
    flex: 12,
  },
  {
    id: 59,
    src: require("@/images/otrosproductos/img59.png"),
    code: "LM-TP059",
    name: "Carpetas en cuero y bio-cuero con telar y grabado",
    flex: 12,
  },
  {
    id: 60,
    src: require("@/images/otrosproductos/img60.png"),
    code: "LM-TP060",
    name: "Taza térmica",
    flex: 12,
  },
  {
    id: 61,
    src: require("@/images/otrosproductos/img61.png"),
    code: "LM-TP061",
    name: "Identificadores",
    flex: 12,
  },
  {
    id: 62,
    src: require("@/images/otrosproductos/img62.png"),
    code: "LM-TP062",
    name: "Lapiceros metálicos con impresión",
    flex: 12,
  },
  {
    id: 63,
    src: require("@/images/otrosproductos/img63.png"),
    code: "LM-TP063",
    name: "Espejo con peine",
    flex: 12,
  },
  {
    id: 64,
    src: require("@/images/otrosproductos/img64.png"),
    code: "LM-TP064",
    name: "Gel Antibacterial",
    flex: 12,
  },
  {
    id: 65,
    src: require("@/images/otrosproductos/img65.png"),
    code: "LM-TP065",
    name: "Llavero pelota antistress",
    flex: 12,
  },
  {
    id: 66,
    src: require("@/images/otrosproductos/img66.png"),
    code: "LM-TP066",
    name: "Llavero metal y cuero",
    flex: 12,
  },
  {
    id: 67,
    src: require("@/images/otrosproductos/img67.png"),
    code: "LM-TP067",
    name: "Tarjetero para celular en silicona",
    flex: 12,
  },
  {
    id: 68,
    src: require("@/images/otrosproductos/img68.png"),
    code: "LM-TP068",
    name: "Tarjetero para celular en silicona",
    flex: 12,
  },
  {
    id: 69,
    src: require("@/images/otrosproductos/img69.png"),
    code: "LM-TP069",
    name: "Lápices colores",
    flex: 12,
  },
  {
    id: 70,
    src: require("@/images/otrosproductos/img70.jpg"),
    code: "LM-TP070",
    name: "Taza con impresión a un color",
    flex: 12,
  },
  {
    id: 71,
    src: require("@/images/otrosproductos/img71.png"),
    code: "LM-TP071",
    name: "Taza con impresión full color",
    flex: 12,
  },
  {
    id: 72,
    src: require("@/images/otrosproductos/img72.png"),
    code: "LM-TP072",
    name: "Pins publicitarios",
    flex: 12,
  },
  {
    id: 73,
    src: require("@/images/otrosproductos/img73.png"),
    code: "LM-TP073",
    name: "Pin publicitario",
    flex: 12,
  },
  {
    id: 74,
    src: require("@/images/otrosproductos/img74.png"),
    code: "LM-TP074",
    name: "Lapicero en metal",
    flex: 12,
  },

  {
    id: 75,
    src: require("@/images/otrosproductos/img75.png"),
    code: "LM-TP075",
    name: "Lápices de colores con tajador",
    flex: 12,
  },{
    id: 76,
    src: require("@/images/otrosproductos/img76.png"),
    code: "LM-TP076",
    name: "Lapiceros con impresión",
    flex: 12,
  },

  {
    id: 77,
    src: require("@/images/otrosproductos/img77.png"),
    code: "LM-TP077",
    name: "Casco antistress con impresión",
    flex: 12,
  },
  {
    id: 78,
    src: require("@/images/otrosproductos/img78.png"),
    code: "LM-TP078",
    name: "Lapicero de madera con impresión",
    flex: 12,
  },
  {
    id: 79,
    src: require("@/images/otrosproductos/img79.png"),
    code: "LM-TP079",
    name: "Aceite aromático",
    flex: 12,
  },
  {
    id: 80,
    src: require("@/images/otrosproductos/img80.png"),
    code: "LM-TP080",
    name: "Cuaderno en cuero repujado",
    flex: 12,
  },
  {
    id: 81,
    src: require("@/images/otrosproductos/img81.png"),
    code: "LM-TP081",
    name: "Gel antibacterial con etiqueta de empresa",
    flex: 12,
  },
  {
    id: 82,
    src: require("@/images/otrosproductos/img82.png"),
    code: "LM-TP082",
    name: "Bloqueador con etiqueta impresa",
    flex: 12,
  },
  {
    id: 83,
    src: require("@/images/otrosproductos/img83.png"),
    code: "LM-TP083",
    name: "Repelente con etiqueta impresa",
    flex: 12,
  },
  {
    id: 84,
    src: require("@/images/otrosproductos/img84.png"),
    code: "LM-TP084",
    name: "Ekeko en cobre con logo",
    flex: 12,
  },
  {
    id: 85,
    src: require("@/images/otrosproductos/img85.png"),
    code: "LM-TP085",
    name: "Lapicero con logo impreso",
    flex: 12,
  },
  {
    id: 86,
    src: require("@/images/otrosproductos/img86.png"),
    code: "LM-TP086",
    name: "Posavaso con logo impreso",
    flex: 12,
  },
  {
    id: 87,
    src: require("@/images/otrosproductos/img87.png"),
    code: "LM-TP087",
    name: "Tarjetero en cobre con logo",
    flex: 12,
  },
  {
    id: 88,
    src: require("@/images/otrosproductos/img88.png"),
    code: "LM-TP088",
    name: "Libreta con impresión",
    flex: 12,
  },
  {
    id: 89,
    src: require("@/images/otrosproductos/img89.png"),
    code: "LM-TP089",
    name: "Carpeta en bio-cuero con impresión",
    flex: 12,
  },
  {
    id: 90,
    src: require("@/images/otrosproductos/img90.png"),
    code: "LM-TP090",
    name: "Carpeta en bio-cuero con repujado",
    flex: 12,
  },
  {
    id: 91,
    src: require("@/images/otrosproductos/img91.png"),
    code: "LM-TP091",
    name: "Taza con diseño",
    flex: 12,
  },
  {
    id: 92,
    src: require("@/images/otrosproductos/img92.png"),
    code: "LM-TP092",
    name: "Monedero en material de neopreno",
    flex: 12,
  },
  {
    id: 93,
    src: require("@/images/otrosproductos/img93.png"),
    code: "LM-TP093",
    name: "Libretas de cuerina",
    flex: 12,
  },
  {
    id: 94,
    src: require("@/images/otrosproductos/img94.png"),
    code: "LM-TP094",
    name: "Libreta biocuero con telar",
    flex: 12,
  },
  {
    id: 95,
    src: require("@/images/otrosproductos/img95.png"),
    code: "LM-TP095",
    name: "Lapiceros porta celular",
    flex: 12,
  },
  {
    id: 96,
    src: require("@/images/otrosproductos/img96.jpg"),
    code: "LM-TP096",
    name: "Cuadro de premiación",
    flex: 12,
  },
  {
    id: 97,
    src: require("@/images/otrosproductos/img97.png"),
    code: "LM-TP097",
    name: "Cuadernos Lego",
    flex: 12,
  },
  {
    id: 98,
    src: require("@/images/otrosproductos/img98.png"),
    code: "LM-TP098",
    name: "Cuaderno Puzzle",
    flex: 12,
  },
  {
    id: 99,
    src: require("@/images/otrosproductos/img99.png"),
    code: "LM-TP099",
    name: "Eco Maceta ecológico con logo en caja",
    flex: 12,
  },
  {
    id: 100,
    src: require("@/images/otrosproductos/img100.jpg"),
    code: "LM-TP100",
    name: "Botella de aluminio y colgador",
    flex: 12,
  },
  {
    id: 101,
    src: require("@/images/otrosproductos/img101.png"),
    code: "LM-TP101",
    name: "Agendas variadas",
    flex: 12,
  },
  {
      id: 102,
      src: require("@/images/otrosproductos/img102.png"),
      code: "LM-TP102",
      name: "Pulsera regla en plástico con metal para imprimir",
      flex: 12,
  },
  {
      id: 103,
      src: require("@/images/otrosproductos/img103.png"),
      code: "LM-TP103",
      name: "Llavero en metal",
      flex: 12,
  },
  {
      id: 104,
      src: require("@/images/otrosproductos/img104.png"),
      code: "LM-TP104",
      name: "Foco antistress",
      flex: 12,
  },
  {
      id: 105,
      src: require("@/images/otrosproductos/img105.png"),
      code: "LM-TP105",
      name: "Monedero en 100% cuero",
      flex: 12,
  },
  {
    id: 106,
    src: require("@/images/otrosproductos/img1.png"),
    name: "Mug de Fibra de Trigo",
    code: "LM-TP106",
    flex: 12,
},
  {
    id: 107,
    src: require("@/images/otrosproductos/img2.png"),
    code: "LM-TP107",
    name: "Arte Urbano de cemento",
    flex: 12,
  },
  {
    id: 108,
    src: require("@/images/otrosproductos/img3.png"),
    code: "LM-TP108",
    name: "Set parrillero portatil",
    flex: 12,
  },
  {
    id: 109,
    src: require("@/images/otrosproductos/img4.png"),
    code: "LM-TP109",
    name: "Libreta de tela y cuerina",
    flex: 12,
  },
  {
    id: 110,
    src: require("@/images/otrosproductos/img5.png"),
    code: "LM-TP110",
    name: "Tomatodo de fibra de trigo ecológico",
    flex: 12,
  },
  {
    id: 111,
    src: require("@/images/otrosproductos/img6.png"),
    code: "LM-TP111",
    name: "Neceser multiusos de poliester",
    flex: 12,
  },
  {
    id: 112,
    src: require("@/images/otrosproductos/img7.jpg"),
    code: "LM-TP112",
    name: "Mug de Fibra de Trigo",
    flex: 12,
  },
  {
    id: 113,
    src: require("@/images/otrosproductos/img107.png"),
    name: "Lápiz natural con impresión a un color",
    code: "LM-TP113",
    flex: 12,
  },
  {
    id: 114,
    src: require("@/images/otrosproductos/img108.png"),
    name: "Canguros cuero",
    code: "LM-TP114",
    flex: 12,
  },
  {
    id: 115,
    src: require("@/images/otrosproductos/img28.png"),
    code: "LM-TP115",
    name: "Libreta biodegradable papel bond con lapicero y Post-it",
    flex: 12,
  },
  {
    id: 116,
    src: require("@/images/otrosproductos/img29.png"),
    code: "LM-TP116",
    name: "Libreta biodegradable",
    flex: 12,
  },
  /*{
      id: 106,
      src: require("@/images/otrosproductos/img106.png"),
      code: "LM-TP106",
      name: "Identificador maleta en bio-cuero con telar",
      flex: 12,
  },*/
]

  export { listOtrosProductos }
